### ISSUE TITLE
Whitelist file

### ISSUE THREAD

**Issue by mertemba** [alx-g/bsrv#2]
Please add an option to specify a whitelist file, i.e. a file that lists files (e.g. newline separated) that are expanded to the `PATH...` command line argument of `borg create`, i.e. added to the `borg_create_args` argument of bsrv.

**Comment by alx-g** [comment]
The next release contains a parameter `borg_create_args_file`. Every line in the supplied file is added to the end of `borg_create_args`. Therefore this can be used as a whitelist file, but may also contain arguments.

**Comment by alx-g** [comment]
Implemented in v0.0.1 (dcebe8430d0f0fa6ca5d3816d6fbf55b5ec449f1)
