### ISSUE TITLE
bsrvd hangs when ssh requires user interaction

### ISSUE THREAD

**Issue by mertemba** [alx-g/bsrv#3]
When the underlying `ssh` requires user interaction (e.g. for host key verification or password input), bsrvd just hangs without any output. Is it possible to run `ssh` so that it fails immediately in those cases?

**Comment by alx-g** [comment]
Will be resolved in upcoming release:
`borg_rsh` now has two implicit options.
One lets `bsrv` use its own known_hosts file (necessary anyway if the user used to run the service has no home directory).
The second one will accept host keys as long as they are new. Changed keys will result in an error.

This results in the following default command (depending on settings)
`ssh -oUserKnownHostsFile="/var/cache/bsrvd/known_hosts" -oStrictHostKeyChecking=accept-new`

As a workaround, these options can be supplied manually in the config file.

**Comment by alx-g** [comment]
Closed in v0.0.1 with dcebe8430d0f0fa6ca5d3816d6fbf55b5ec449f1
